defaults: &defaults
  port: 3000
  max_age: 300
  shortkey : def

development:
  shortkey : dev
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  port: 80
  shortkey : prod
  <<: *defaults
